### ISSUE TITLE
Bug: issue with video download from youtube - bot detection

### ISSUE THREAD

**Issue by aliraza-noon** [omeryusufyagci/fast-music-remover#83]
**Describe the bug**

I deployed an instance of this on fly.io and tried with some random video with noise I was getting an error on the UI i checked the logs the script is not able to download vidoes from youtube*

**To Reproduce**
1. Deploy an instance on fly.io
2. Open the url from the flyio console
3. Try with a video from youtube
4. Notice the error on UI

**Expected behavior**
It should work with videos from youtube out of the box

**Logs and Debug Information**

```

2024-12-05T12:08:53.205 app[784e671be64418] bom [info] [youtube] Extracting URL: https://www.youtube.com/watch?v=US4Zr1WKD-8

2024-12-05T12:08:53.205 app[784e671be64418] bom [info] [youtube] US4Zr1WKD-8: Downloading webpage

2024-12-05T12:08:53.897 app[784e671be64418] bom [info] [youtube] US4Zr1WKD-8: Downloading ios player API JSON

2024-12-05T12:08:54.016 app[784e671be64418] bom [info] [youtube] US4Zr1WKD-8: Downloading web creator player API JSON

2024-12-05T12:08:54.168 app[784e671be64418] bom [info] ERROR: [youtube] US4Zr1WKD-8: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

2024-12-05T12:08:54.169 app[784e671be64418] bom [info] ERROR:root:Error downloading video: ERROR: [youtube] US4Zr1WKD-8: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

2024-12-05T12:08:54.170 app[784e671be64418] bom [info] 172.16.19.74 - - [05/Dec/2024 12:08:54] "POST / HTTP/1.1" 200 -

2024-12-05T12:08:54.170 app[784e671be64418] bom [info] INFO:werkzeug:172.16.19.74 - - [05/Dec/2024 12:08:54] "POST / HTTP/1.1" 200 -

```

**Screenshots**

<img width="728" alt="Screenshot 2024-12-05 at 4 14 50 PM" src="https://github.com/user-attachments/assets/44c5fe49-e4a4-4103-aa26-ca699c6d5fbf">

**System and software (please complete the following information):**
 - OS: Linux
 - Output of `ffmpeg -version` : not able to get this 

**Additional context**
Please include system settings, configuration changes, or anything else you believe might contribute to the problem.

**Comment by omeryusufyagci** [comment]
Hi @aliraza-noon, thanks for reporting this and the details. 

Unfortunately, it looks like you've been flagged by YT. I'm not familiar with fly.io, but from what we anectodally know, some platforms such as YT are aggressively flagging datacenter IPs and the like. So, it could be, that either you're hosting this on a susceptible IP, or you've been trying to download too much, too fast. 

The logs you see are directly coming from the extractor we're using, `yt-dlp`. It's a known problem/limitation and you can find similar information [here](https://github.com/yt-dlp/yt-dlp/issues/10128). 

I'm afraid this is not something we, within fast music remover, could solve, but what I could suggest trying is perhaps using a VPN or trying it on your local machine. In addition, refrain from passing your cookies as a _workaround_, as that could lead you getting cookie-banned.

It'd be best practice to limit the download requests just in case. I haven't had such an issue and I've been testing extensively since some time (months), on multiple machines. 

I'm sorry I couldn't solve your issue directly, but I hope this helps you to use FMR!

**Comment by aliraza-noon** [comment]
hey, thanks for the reply.

it is unlikely that this got todo with the downloading/rate-limiting as this is the only video url I tried maybe 2,3 times with a gap of few seconds ~30. 

Though what you said about datacenter ips that makes sense there could be folks using these hosting services to build scrappers etc and google is probably already aware of these ips.

**Comment by aliraza-noon** [comment]
I tried to run it locally as well, I did not run the the whole docker image as I don't have docker installed , I tried to build the media processor from source on mac, with that too I was not very successful some issue with the linker

**Comment by omeryusufyagci** [comment]
Hi @aliraza-noon,

Thanks for the feedback!
It's likely the IP that was flagged then... 

If you're on macOS, you could install docker desktop [here](https://docs.docker.com/desktop/setup/install/mac-install/), if it's an option. That'd be all you'd need; just keep it running when you want to run images locally. 

Otherwise, I've very recently fixed a deprecation error on clang compiler which is likely what you have on macOS. 
So, another option would be to do a `git fetch origin; git pull origin main` to ensure you're on the latest version, and try again. I'd be happy to help out on resolving the linker error.

I've held off on the release as we're very close on adding even better tooling and major additions to the API. It shouldn't be too long until that happens. In the meantime, the easiest option would be install docker and run the image locally.

**Comment by aliraza-noon** [comment]
I will give this shot again over the weekend, thanks for once again

if I can get this to run it will be major help for me I have some free lectures on youtube that I like to watch with better audio 😃

**Comment by aliraza-noon** [comment]
I know you have plans to add support for realtime playback,  do you have any docs that outline how it is gonna work technically ?

**Comment by omeryusufyagci** [comment]
> if I can get this to run it will be major help for me I have some free lectures on youtube that I like to watch with better audio

That makes me excited! We have decent support for most modern hardware, and I'm here to help you with any issues that you may face -not that I expect any! 

I'll close this particular issue as the problem was understood to be solely induced by external conditions we cannot control within FMR. However, please don't hesitate to get in touch here or ping me on our [discord server](https://discord.gg/xje3PQTEYp)! 

> I know you have plans to add support for realtime playback, do you have any docs that outline how it is gonna work technically ?

Indeed, we'll dedicate some resources there after our pending release. There are a few areas that we've yet to explore, and not much has been documented as of now (you can see open issues for the ones that were). 

I've done early tests to take a continuous stream of data and process without delay, and it _works_, but we'll have to cut down on the OS calls we're making as they introduce uncertainties that simply won't work for a realtime system. Let me know if you have anything specific in mind!
