### ISSUE TITLE
Bug: ERROR:root:MediaProcessor stderr

### ISSUE THREAD

**Issue by alexgorbatchev** [omeryusufyagci/fast-music-remover#84]
**Describe the bug**
seeing this for any youtube url or manually uploading files into the UI from the `/app/uploads` folder.

```
ERROR:root:MediaProcessor stderr
ERROR:root:MediaProcessor returned a non-zero exit code.
```

**To Reproduce**
1. using this URL for example https://www.youtube.com/watch?v=ZALtzTmPz-E

**Expected behavior**
obviously expecting no errors

**Logs and Debug Information**
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=ZALtzTmPz-E
[youtube] ZALtzTmPz-E: Downloading webpage
[youtube] ZALtzTmPz-E: Downloading ios player API JSON
[youtube] ZALtzTmPz-E: Downloading web creator player API JSON
[youtube] ZALtzTmPz-E: Downloading m3u8 information
[info] ZALtzTmPz-E: Downloading 1 format(s): 616+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 33
[download] Destination: /app/uploads/Hrdza_-__tefan___Stephen_________.f616.mp4
[download] 100% of   81.88MiB in 00:00:04 at 18.91MiB/s
[download] Destination: /app/uploads/Hrdza_-__tefan___Stephen_________.f251.webm
[download] 100% of    2.65MiB in 00:00:00 at 38.54MiB/s
[Merger] Merging formats into "/app/uploads/Hrdza_-__tefan___Stephen_________.webm"
ERROR:root:MediaProcessor stderr:
ERROR:root:MediaProcessor returned a non-zero exit code.
```

**Screenshots**

**System and software (please complete the following information):**
- `docker run -p 8080:8080 -v ./uploads:/app/uploads ghcr.io/omeryusufyagci/fast-music-remover:latest`
- `Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000 arm64`

**Comment by omeryusufyagci** [comment]
Hi @alexgorbatchev, thank you very much for reporting this. This turned out to be quite an interesting one... 

Although we provide a docker container to avoid platform specific issues, unfortunately, this appears to be one. 
There was initially an issue with one of our internal libraries using a set of x86_64 CPU instructions which would not be properly emulated on macOS (some details in the PRs; limitations of QEMU-based Docker emulation, apparently a known issue). 
Removing the optimization on the library I could fix the issue and was able to run it locally. 
There is now a secondary issue, a behavior discrepancy of the image between my local machine and the one from the GHCR. I think the GH workflow is doing things a little differently and I'll have to work in this for a bit more.

I'm sorry that you couldn't use the application, and this was something quite unexpected to me at least. 
In the meantime, you could try to launch it from a Linux machine if you have access to one, or the following also works when launched locally.
From the repo root:
```
docker build --platform linux/amd64 -t ghcr.io/omeryusufyagci/fast-music-remover:latest .
docker run --platform linux/amd64 -p 8080:8080 -it ghcr.io/omeryusufyagci/fast-music-remover:latest
```
Quite interestingly, the same set of instructions produce a different result on the CI...or maybe I'm missing something obvious as I've staring at this for quite some time now!

Thanks again for the report, and I'll try to resolve this soon.

**Comment by omeryusufyagci** [comment]
Hi @alexgorbatchev, 

First off, many thanks again for this report! 
After prematurely thinking I fixed this, and discovering some new problems, now I believe the issue is solved for good. 
I updated both the dockerfile and the release workflow, and you can see #89 for some details if you wish.

**In short**: The `latest` image now supports both amd64 and arm64 out of the box and I tested it OK on an arm64 macos machine after a prune. So, it should be ready for you, and it'd be great if you could give it another try!
